import Header from '@/components/header';
import { Prompt } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';

const prompt = Prompt({
	subsets: ['thai'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={prompt.className}>
				<Header />
				{children}
				{/* <main className="container mx-auto bg-gray-100">{children}</main> */}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
