import type { Metadata } from 'next';

import Footer from '@/components/footer';
import Header from '@/components/header';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-prompt">
				<Header />
				<main className="container mx-auto bg-gray-100">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
